<script setup lang="ts">
const props = defineProps<{ events: any[] }>()
const view = ref<'week' | 'list'>('week')
const selected = ref<any>(null)
const copied = ref(false)
function open(event: any) { selected.value = event; copied.value = false }
async function copy() { if (!selected.value) return; await navigator.clipboard.writeText(selected.value.content); copied.value = true }
const dayName = (date: string) => new Date(`${date}T12:00:00`).toLocaleDateString(undefined, { weekday: 'short' })
</script>
<template>
  <div>
    <div class="mb-5 flex items-center justify-between"><div><h2 class="text-xl font-bold">Your 7-day publishing plan</h2><p class="mt-1 text-sm text-slate-400">A deterministic schedule built from your campaign strategy and QA-checked assets.</p></div><div class="rounded-xl border border-slate-700 bg-slate-900 p-1 text-xs font-semibold"><button class="rounded-lg px-3 py-2" :class="view === 'week' ? 'bg-cyan-400 text-slate-950' : 'text-slate-400'" @click="view = 'week'">Week</button><button class="rounded-lg px-3 py-2" :class="view === 'list' ? 'bg-cyan-400 text-slate-950' : 'text-slate-400'" @click="view = 'list'">List</button></div></div>
    <div v-if="view === 'week'" class="grid gap-3 sm:grid-cols-2 lg:grid-cols-7"><button v-for="event in events" :key="event.asset_id" class="min-h-64 rounded-2xl border border-slate-700 bg-slate-900/60 p-4 text-left transition hover:border-cyan-400" @click="open(event)"><p class="text-xs font-bold uppercase tracking-wider text-cyan-300">{{ dayName(event.date) }} · Day {{ event.day }}</p><p class="mt-1 text-xs text-slate-500">{{ event.date }}</p><p class="mt-5 text-sm font-semibold capitalize">{{ event.platform }}</p><p class="mt-1 text-xs text-slate-400">{{ event.content_type.replace('_', ' ') }}</p><h3 class="mt-4 line-clamp-3 font-semibold">{{ event.title }}</h3><div class="mt-5 space-y-2 text-xs"><p><span class="text-slate-500">Goal</span> · <span class="capitalize text-slate-200">{{ event.objective }}</span></p><p><span class="text-slate-500">Time</span> · {{ event.recommended_time }}</p><p v-if="event.qa_score"><span class="text-slate-500">QA</span> · <span class="text-emerald-300">{{ event.qa_score }}%</span></p><span class="inline-block rounded-full bg-emerald-950 px-2 py-1 text-emerald-300" :class="event.status === 'REVIEW' ? 'bg-amber-950 text-amber-300' : ''">{{ event.status }}</span></div></button></div>
    <div v-else class="divide-y divide-slate-800 rounded-2xl border border-slate-800"><button v-for="event in events" :key="event.asset_id" class="flex w-full flex-col gap-3 p-5 text-left transition hover:bg-slate-900 sm:flex-row sm:items-center" @click="open(event)"><div class="w-32 text-sm"><p class="font-semibold">{{ dayName(event.date) }}</p><p class="text-slate-500">{{ event.date }}</p></div><div class="flex-1"><p class="text-xs font-bold uppercase text-cyan-300">{{ event.platform }} · {{ event.content_type }}</p><h3 class="mt-1 font-semibold">{{ event.title }}</h3><p class="mt-1 text-sm text-slate-400">{{ event.objective }} · {{ event.recommended_time }}</p></div><div class="text-sm"><p v-if="event.qa_score" class="text-emerald-300">QA {{ event.qa_score }}%</p><p class="text-slate-400">{{ event.status }}</p></div></button></div>
    <div v-if="selected" class="fixed inset-0 z-50 flex justify-end bg-slate-950/70" @click.self="selected = null"><aside class="h-full w-full max-w-xl overflow-y-auto border-l border-slate-700 bg-slate-950 p-7 shadow-2xl"><button class="text-sm text-slate-400 hover:text-white" @click="selected = null">← Close</button><p class="mt-8 text-xs font-bold uppercase tracking-wider text-cyan-300">{{ selected.platform }} · {{ selected.content_type }}</p><h2 class="mt-2 text-2xl font-bold">{{ selected.title }}</h2><div class="mt-5 grid grid-cols-2 gap-3 rounded-xl bg-slate-900 p-4 text-sm"><p><span class="text-slate-500">Objective</span><br><span class="capitalize">{{ selected.objective }}</span></p><p><span class="text-slate-500">Scheduled</span><br>{{ selected.date }} · {{ selected.recommended_time }}</p></div><p class="mt-6 whitespace-pre-wrap leading-7 text-slate-200">{{ selected.content }}</p><p v-if="selected.cta" class="mt-4 text-cyan-200">{{ selected.cta }}</p><section class="mt-7 rounded-xl border border-slate-800 p-4"><h3 class="font-semibold">Content QA</h3><p v-if="selected.qa_score" class="mt-2 text-2xl font-bold text-emerald-300">{{ selected.qa_score }}% <span class="text-sm font-normal text-slate-400">faithfulness</span></p><p v-else class="mt-2 text-sm text-slate-400">QA has not been run yet.</p><p v-if="selected.unsupported_claims?.length" class="mt-3 text-sm text-amber-300">Review: {{ selected.unsupported_claims.length }} unsupported claim(s) found.</p><p v-else-if="selected.qa_score" class="mt-3 text-sm text-emerald-300">✓ No unsupported claims found.</p></section><div class="mt-7 flex gap-3"><button class="rounded-lg bg-cyan-400 px-4 py-2.5 text-sm font-bold text-slate-950" @click="copy">{{ copied ? 'Copied' : 'Copy content' }}</button><NuxtLink :to="`/campaigns/${selected.campaign_id || ''}/assets`" class="rounded-lg border border-slate-700 px-4 py-2.5 text-sm font-semibold">Open assets</NuxtLink></div></aside></div>
  </div>
</template>
